apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: resources-burner
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: resources-burner
    app.kubernetes.io/part-of: load-app-d9ef65c2-ea40-443f-9197-c47b90ccc35a
  name: resources-burner
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: resources-burner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: resources-burner
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-100-tenant/load-app-d9ef65c2-ea40-443f-9197-c47b90ccc35a/resources-burner@sha256:fcc1be64bef10fe751590b27681627e297605c8b82e42527ae2e095ab3d95e71
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
